version: '2.3'
services:
  carla_env0:
    image: carlasim/carla:0.8.2
    runtime: nvidia
    command: ./CarlaUE4.sh -carla-server -fps=30
    networks:
      - carla_net0
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  policy_image0:
    image: onlytailei/pytorch:0.4.1-cuda9-tensorboardx
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
    volumes:
      - ${TAI_CARLA}:/home/carla/
    networks:
      - carla_net0
    working_dir: /home/carla/PythonClient/imitation_learning/
    command:
        python run_CIL.py
        --host carla_env0
        --log-name clear_best
        --weathers 1
        --model-path "model_policy/clear_policy_best.pth"

  carla_env1:
    image: carlasim/carla:0.8.2
    runtime: nvidia
    command: ./CarlaUE4.sh -carla-server -fps=30
    networks:
      - carla_net0
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  policy_image1:
    image: onlytailei/pytorch:0.4.1-cuda9-tensorboardx
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
    volumes:
      - ${TAI_CARLA}:/home/carla/
    networks:
      - carla_net0
    working_dir: /home/carla/PythonClient/imitation_learning/
    command:
        python run_CIL.py
        --host carla_env1
        --log-name clear_last
        --weathers 1
        --model-path "model_policy/clear_policy_last.pth"

  carla_env2:
    image: carlasim/carla:0.8.2
    runtime: nvidia
    command: ./CarlaUE4.sh -carla-server -fps=30
    networks:
      - carla_net0
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  policy_image2:
    image: onlytailei/pytorch:0.4.1-cuda9-tensorboardx
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
    volumes:
      - ${TAI_CARLA}:/home/carla/
    networks:
      - carla_net0
    working_dir: /home/carla/PythonClient/imitation_learning/
    command:
        python run_CIL.py
        --host carla_env2
        --log-name wet_best
        --weathers 3
        --model-path "model_policy/wet_policy_best.pth"

  carla_env3:
    image: carlasim/carla:0.8.2
    runtime: nvidia
    command: ./CarlaUE4.sh -carla-server -fps=30
    networks:
      - carla_net0
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  policy_image3:
    image: onlytailei/pytorch:0.4.1-cuda9-tensorboardx
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
    volumes:
      - ${TAI_CARLA}:/home/carla/
    networks:
      - carla_net0
    working_dir: /home/carla/PythonClient/imitation_learning/
    command:
        python run_CIL.py
        --host carla_env3
        --log-name wet_last
        --weathers 3
        --model-path "model_policy/wet_policy_last.pth"

networks:
  carla_net0:
    external: true
