version: '3'
services:
  carla_env:
    image: carlasim/carla:0.8.2
    networks:
      - carla_net
    command: ./CarlaUE4.sh -carla-server -fps=30

  # benchmark:
  #   image: onlytailei/pytorch:0.4.1-cuda9-tensorboardx
  #   volumes:
  #     - ${TAI_CARLA}:/home/carla/
  #   networks:
  #     - carla_net
  #   entrypoint: /bin/bash
  #   working_dir: /home/carla/PythonClient/imitation-learning
  #   command: python run_CIL.py
  #   ports:
  #     - "6007:6006"

networks:
  carla_net:
    external: true
